<?php

function notify($to,$data){

    $api_key="AAAAW5OFEL4:APA91bH96KCkVom6EMOms0QXWyS-otWxDZcbf91WaCKIEDrg0zNMx6ekdLcQDg_8iqT0BJamhMFgdUDgiXU8Z0lgx7uOXnhKvT_EFY7q6r9H6g7G1S1fvOeEiAnxnwtfJUzooa9ENQbA";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$to="dk48ijHyRECwQ5pNwSJQo5:APA91bGmsWx12QCQEs_G-7c_t5iXLWdBJUixGW44uHLra2oVbTiM5xt5Mp_lT1llAxWS3neu7JEZ9vaupI7CMG5aNN5fBLEk1ePQZ7wHjxQrYLUpZU6FgxFe_yCmDDKRbXOxMCqpfJt6";
$data=array(
    'title'=>'Regu',
    'body'=>'Hola, ya funciona'
);

notify($to,$data);
echo "Notification Sent";

?>
